version: '3'

services:
  parser:
    build: ./parlamint-parser
    depends_on:
      - parladata
    volumes:
      - ./parlamint-parser/data/:/app/data/

  parladata:
    build: ./parladata
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
      DJANGO_SETTINGS_MODULE: parladata_project.settings.k8s
      DJANGO_SECRET_KEY: make-me-secret
      DJANGO_DATABASE_HOST: db
      PARLADATA_URL: http://localhost:8000/v1
      PARLALIZE_URL: http://localhost:8080/v1
      ISCI_URL: http://localhost:8888/
      PARLAMETER_URL: https://parlameter.si/
      CARDS_URL: https://glej.parlameter.si/
      NOTIFICATIONS_URL: https://obvestila.parlameter.si/
      PARLAMETER_SOLR_URL: http://solr:8983/solr/parlasearch

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: parladata
    ports:
      - 5432:5432

  solr:
    build: ./parlasearch/solr
    ports:
      - 8983:8983
    volumes:
      - ./parlasearch/solr/parlasearch-conf:/parlasearch-conf

  parlanode:
    build: ./parlanode
    ports:
      - 3000:3000
      - 7004:7004
    environment:
      # development server port
      VITE_PORT: "3000"
      # base url for loading assets
      VITE_PARLASSETS_URL: https://cdn.nov.parlameter.si/v1/parlassets
      # base url for fetching data
      VITE_PARLADATA_URL: http://parladata:8000/v3
      # self base url
      VITE_PARLACARDS_URL: http://localhost:7004
      # main site url
      VITE_PARLASITE_URL: http://localhost:3066
      # production server port
      PORT: "7004"

  parlasite:
    build: ./parlasite
    ports:
      - 3066:3066
    environment:
      NODE_ENV: development
      MAIN_ORG_ID: "1"
      MANDATE_ID: "1"
    depends_on:
      - parladata
